### ISSUE TITLE
Could it be possible to have Assist support?

### ISSUE THREAD

**Issue by jukefr** [Willow-Systems/pebble-home-assistant#11]
Hey,
First let me say thank you so much for this app and helping keep the pebble ecosystem alive :D

HA has been focusing a bit more lately on "voice assistant" and have added [Assist](https://www.home-assistant.io/blog/2023/01/26/year-of-the-voice-chapter-1/) and integrations with [Whisper](https://github.com/openai/whisper) and [Piper](https://github.com/rhasspy/piper), meaning you can now give it vocal commands to trigger things.
It is still very basic and the default intentions are like, almost inexistant, you can turn off and on your devices and maybe set light brightness.
But still, the foundation for it becoming a bit more useful in the months/years to come is there.

I was wondering if you had heard of this, and if you think it would be conceivable/useful/doable to add support for it (Assist) on the pebble app?
This way you could use your watch just like we used to with [Snowy](https://mydogsnowy.com/) to do a bunch of things directly with voice.

I would love to contribute in any way to this if possible but sadly I'm more of a high level programming language person and C is completely out of my depth, but please let me know if there's anything I could do potentially to help with this (if it's something you are interesting in supporting). I do know my way around js if that can help.

Here is another link on what it looks like on the android wear companion thing https://www.home-assistant.io/docs/assist/android

Thank you in advance for any response.

**Comment by cgbaker** [comment]
I'd like to take this work on. With the caveat that I haven't done any Pebble development before, it seems like it should be straightforward to use the Pebble [Dictation API](https://developer.rebble.io/developer.pebble.com/guides/events-and-services/dictation/index.html) to get a command and send that to the Home Assistant [Conversation API](https://developers.home-assistant.io/docs/intent_conversation_api/).

However, I've struggled a bit just to start development here; a lot of the instructions for setting up a Pebble development environment are seriously out-of-date. I've joined the Discord server to look for help; if I get this working, I'll submit a PR. Otherwise, if you have any pointers, I'd appreciate them.

Update: I found recent instructions for setting up a dev environment: https://github.com/andyburris/pebble-setup

**Comment by Willow-Systems** [comment]
I took the awesome work @cgbaker did and tweaked the UI, and now version 1.14 is live on the Rebble appstore!

You should just get the update automatically @jukefr! If not just reinstall the app from the appstore

![image](https://github.com/Willow-Systems/pebble-home-assistant/assets/24474651/5a60c71a-dac1-4ba4-b33d-f09db198eb58)

**Comment by jukefr** [comment]
Thank you very much for this @cgbaker and @Willow-Systems! 
I'm trying to figure it out and seems that I still have everything working on HA side, but cannot get it to process speech with the watch app.
Is a rebble.io subscription required for the voice service? (I am on free tier and cannot really afford even the $3/month these days :sweat_smile:) Is there any possibility the raw voice clip could be forwarded to HA directly (is that even possible with the SDK?), keeping the default to rebble STT but having the option to use HA STT if wanted because I have the voice processing pipeline all setup and running locally on there with [Whisper](https://github.com/openai/whisper).
I do not know which would be faster or better but in my case its also a lot more about not having my voice sent to some 3rd party for processing, it's more of a personal data ownership/rights thing :sweat_smile:
Sorry if being a bother about this let me know if I should open a separate thread about this. If its actually possible to just send the raw voice clip over I might also try to contribute a PR because I saw that most of the work done was in js and i mistakenly thought it would be C ^^

**Comment by cgbaker** [comment]
The Dictation API is supported by a cloud transcriber, which requires a Rebble subscription to support the costs. ☹️ 

I was thinking about doing the transcription in HA, but the Dictation API doesn't appear to support customizable transcribers, even in C:
https://developer.rebble.io/developer.pebble.com/guides/events-and-services/dictation/index.html
Furthermore, as far as I can tell, the only access to the microphone is through the Dictation API; I don't know if this would require modifications to the SDK or changes to the firmware; it's probably worth asking in those projects.

If we could get access to the microphone, it may be possible to set up the pebble as a media device and use it for custom Voice Assistant pipelines using local TTS. I'm content with this solution for now; but if you get any leeway with other projects, let me know and I'd be glad to take another look.
