### ISSUE TITLE
Cannot set the URL within the app

### ISSUE THREAD

**Issue by Fluffy-Bean** [Willow-Systems/pebble-home-assistant#15]
![Screenshot_20240606-103813.png](https://github.com/Willow-Systems/pebble-home-assistant/assets/86935712/81305817-64ef-401e-992e-892bb91eff6f)

**Comment by Fluffy-Bean** [comment]
My bad, opened the issue for the wrong repository 😓

**Comment by Willow-Systems** [comment]
Which app are you having issues with?

**Comment by Fluffy-Bean** [comment]
I installed [the wrong one by accident](https://apps.rebble.io/en_US/application/5a4533bf461a8d60350019d9?query=homeassistant&section=watchapps), as when I searched the app store for "home assistant", only one result shown up, so I assumed it was yours.

Only after I opened this issue I noticed in your README that there is multiple home assistant apps available

But managed to figure it out now '^^
