### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by adocampo** [Willow-Systems/pebble-home-assistant#3]
Hi there, 

Just stumbled upon this project, and I was wondering if there are any installation method to try it by myself.

Thank you.

**Comment by Willow-Systems** [comment]
Hey. No idea if this is still of interest for you, but as part of a Rebble Hackathon I finished this app, and it's now [live on the store](https://apps.rebble.io/en_US/application/637a99d0fdf3e30009f6397d).

**Comment by adocampo** [comment]
¡Awesome! It works flawlessly! 
Now my wife and I are able to control lights and switches from our wrists! 

Thank you very much!
