### ISSUE TITLE
Feature Request - Scene Support

### ISSUE THREAD

**Issue by doakyz** [Willow-Systems/pebble-home-assistant#5]
Loving the app so far, just adding a request in for scene support in the future :)

Keep up the amazing work <3

**Comment by Willow-Systems** [comment]
This shouldn't be too hard! I'll add it to the next release :)

**Comment by Willow-Systems** [comment]
Scene support is added! Your app should auto update, once you're on version 1.2 you'll see Scenes as an option from the home screen
